gsap.from(".title", { opacity: 0, y: -50, duration: 1 })
gsap.from(".sub", { opacity: 0, y: 40, duration: 1, delay: .2 })
gsap.from(".info-box", { opacity: 0, scale: .5, duration: 1, delay: .4 })
gsap.from("#classes .card", { opacity: 0, y: 50, duration: .8, stagger: .2, delay: .6 })
gsap.from("#faculty .card", { opacity: 0, y: 50, duration: .8, stagger: .2, delay: .8 })
gsap.from("#testimonials .card", { opacity: 0, y: 50, duration: .8, stagger: .2, delay: 1 })
gsap.from(".contact-form", { opacity: 0, scale: .7, duration: 1, delay: 1.2 })
gsap.from(".btn", { opacity: 0, scale: .5, duration: 1, delay: 1.4 })
gsap.from(".whatsapp-btn", { opacity: 0, x: 50, duration: 1, delay: 1.6 })